import { type DataFetcher } from "../types/DataFetcher";
import { type Degree } from "../types/Degree";
import { type Requirement } from "../types/Requirement";

export class FakeDataFetcher implements DataFetcher {
  getDegreeId = (): number | null => {
    const urlParams = new URLSearchParams(window.location.search);
    const degreeId = urlParams.get("Degree_ID");
    return degreeId ? parseInt(degreeId) : null;
  };
  getDegree = async (degreeId: number | null): Promise<Degree | undefined> => {
    await new Promise((resolve) => setTimeout(resolve, 50));
    return degree.ID === degreeId ? degree : undefined;
  };
  getRequirements = async (degreeId: number | null): Promise<Requirement[]> => {
    await new Promise((resolve) => setTimeout(resolve, 200));
    return degreeId === 10007 ? requirements : [];
  };
}

const degree: Degree = {
  ID: 10007,
  Name: "Bachelor of Science in Computer Science",
  College: "College of Engineering",
  AcademicYears: "2023-2024",
};

const requirements: Requirement[] = [
  {
    ID: 1,
    Year: 1,
    SortOrder: 1,
    SubjectAbbreviation: "CHEM",
    SubjectIsActive: true,
    CourseNumber: "1111",
    CourseName: "Fundamentals of Chemistry Lab",
    CourseDescription: "",
    CourseCreditHours: 1,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 2,
    Year: 1,
    SortOrder: 2,
    SubjectAbbreviation: "CHEM",
    SubjectIsActive: true,
    CourseNumber: "1311",
    CourseName: "Fundamentals of Chemistry",
    CourseDescription: "Introduces the basic principles of chemistry.",
    CourseCreditHours: 3,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 3,
    Year: 1,
    SortOrder: 3,
    SubjectAbbreviation: "ENGI",
    SubjectIsActive: true,
    CourseNumber: "1100",
    CourseName: "Introduction to Engineering",
    CourseDescription: "Overview of the engineering profession.",
    CourseCreditHours: 1,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 4,
    Year: 1,
    SortOrder: 4,
    SubjectAbbreviation: "ENGL",
    SubjectIsActive: true,
    CourseNumber: "1301",
    CourseName: "First Year Writing I",
    CourseDescription: "Principles of academic writing.",
    CourseCreditHours: 3,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 5,
    Year: 1,
    SortOrder: 5,
    SubjectAbbreviation: "HIST",
    SubjectIsActive: true,
    CourseNumber: "1301",
    CourseName: "The United States To 1877",
    CourseDescription:
      "History of the United States from its founding to 1877.",
    CourseCreditHours: 3,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 6,
    Year: 1,
    SortOrder: 6,
    SubjectAbbreviation: "MATH",
    SubjectIsActive: true,
    CourseNumber: "2413",
    CourseName: "Calculus I",
    CourseDescription: "Limits, derivatives, and an introduction to integrals.",
    CourseCreditHours: 4,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 7,
    Year: 1,
    SortOrder: 1,
    SubjectAbbreviation: "ENGI",
    SubjectIsActive: true,
    CourseNumber: "1331",
    CourseName: "Computing for Engineers",
    CourseDescription: "Introduction to computer programming for engineers.",
    CourseCreditHours: 3,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 8,
    Year: 1,
    SortOrder: 2,
    SubjectAbbreviation: "ENGL",
    SubjectIsActive: true,
    CourseNumber: "1302",
    CourseName: "First Year Writing II",
    CourseDescription: "Research and argumentation in academic writing.",
    CourseCreditHours: 3,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 9,
    Year: 1,
    SortOrder: 3,
    SubjectAbbreviation: "HIST",
    SubjectIsActive: true,
    CourseNumber: "1302",
    CourseName: "The United States Since 1877",
    CourseDescription:
      "History of the United States since the Reconstruction era.",
    CourseCreditHours: 3,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 10,
    Year: 1,
    SortOrder: 4,
    SubjectAbbreviation: "MATH",
    SubjectIsActive: true,
    CourseNumber: "2414",
    CourseName: "Calculus II",
    CourseDescription: "Techniques of integration and infinite series.",
    CourseCreditHours: 4,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 11,
    Year: 1,
    SortOrder: 5,
    SubjectAbbreviation: "PHYS",
    SubjectIsActive: true,
    CourseNumber: "2325",
    CourseName: "University Physics I",
    CourseDescription: "Mechanics and thermodynamics.",
    CourseCreditHours: 3,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 12,
    Year: 1,
    SortOrder: 6,
    SubjectAbbreviation: "PHYS",
    SubjectIsActive: true,
    CourseNumber: "2125",
    CourseName: "University Physics Laboratory I",
    CourseDescription: "Experiments in mechanics and thermodynamics.",
    CourseCreditHours: 1,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 13,
    Year: 2,
    SortOrder: 1,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "2201",
    CourseName: "Circuit Analysis I",
    CourseDescription: "Fundamental principles of circuit analysis.",
    CourseCreditHours: 2,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 14,
    Year: 2,
    SortOrder: 2,
    SubjectAbbreviation: "MATH",
    SubjectIsActive: true,
    CourseNumber: "2415",
    CourseName: "Calculus III",
    CourseDescription: "Multivariable calculus.",
    CourseCreditHours: 4,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 15,
    Year: 2,
    SortOrder: 3,
    SubjectAbbreviation: "MATH",
    SubjectIsActive: true,
    CourseNumber: "3321",
    CourseName: "Engineering Mathematics",
    CourseDescription: "Differential equations and linear algebra.",
    CourseCreditHours: 3,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 16,
    Year: 2,
    SortOrder: 4,
    SubjectAbbreviation: "PHYS",
    SubjectIsActive: true,
    CourseNumber: "2326",
    CourseName: "University Physics II",
    CourseDescription: "Electricity and magnetism.",
    CourseCreditHours: 3,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 17,
    Year: 2,
    SortOrder: 5,
    SubjectAbbreviation: "PHYS",
    SubjectIsActive: true,
    CourseNumber: "2126",
    CourseName: "University Physics Laboratory II",
    CourseDescription: "Experiments in electricity and magnetism.",
    CourseCreditHours: 1,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 18,
    Year: 2,
    SortOrder: 6,
    SubjectAbbreviation: "GOVT",
    SubjectIsActive: true,
    CourseNumber: "2306",
    CourseName: "U.S. & TX Constitution / Politics",
    CourseDescription: "Principles of American and Texas government.",
    CourseCreditHours: 3,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 19,
    Year: 2,
    SortOrder: 1,
    SubjectAbbreviation: "ENGI",
    SubjectIsActive: true,
    CourseNumber: "2304",
    CourseName: "Technical Communications",
    CourseDescription: "Communication techniques for engineers.",
    CourseCreditHours: 3,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 20,
    Year: 2,
    SortOrder: 2,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "2202",
    CourseName: "Circuit Analysis II",
    CourseDescription: "Advanced circuit analysis techniques.",
    CourseCreditHours: 2,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 21,
    Year: 2,
    SortOrder: 3,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "2100",
    CourseName: "Circuit Analysis Laboratory",
    CourseDescription: "Experiments in circuit analysis.",
    CourseCreditHours: 1,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 22,
    Year: 2,
    SortOrder: 4,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "3331",
    CourseName: "Programming Applications in ECE",
    CourseDescription:
      "Computer programming for electrical and computer engineers.",
    CourseCreditHours: 3,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 23,
    Year: 2,
    SortOrder: 5,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "3441",
    CourseName: "Digital Logic Design",
    CourseDescription: "Design and implementation of digital systems.",
    CourseCreditHours: 4,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 24,
    Year: 2,
    SortOrder: 6,
    SubjectAbbreviation: "CORE",
    SubjectIsActive: true,
    CourseNumber: "",
    CourseName: "Creative Arts",
    CourseDescription: "Introduction to visual and performing arts.",
    CourseCreditHours: 3,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 25,
    Year: 3,
    SortOrder: 1,
    SubjectAbbreviation: "COSC",
    SubjectIsActive: true,
    CourseNumber: "1437",
    CourseName: "Intro to Programming",
    CourseDescription: "Fundamental concepts of programming.",
    CourseCreditHours: 4,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 26,
    Year: 3,
    SortOrder: 2,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "3155",
    CourseName: "Electronics Lab",
    CourseDescription: "Experiments in electronics.",
    CourseCreditHours: 1,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 27,
    Year: 3,
    SortOrder: 3,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "3355",
    CourseName: "Electronics",
    CourseDescription: "Electronic devices and circuits.",
    CourseCreditHours: 3,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 28,
    Year: 3,
    SortOrder: 4,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "3436",
    CourseName: "Microprocessors",
    CourseDescription: "Microprocessor architecture and programming.",
    CourseCreditHours: 4,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 29,
    Year: 3,
    SortOrder: 5,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "3337",
    CourseName: "Signal & System Analysis",
    CourseDescription: "Analysis of signals and systems.",
    CourseCreditHours: 3,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 30,
    Year: 3,
    SortOrder: 6,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "3317",
    CourseName: "Applied EM Waves",
    CourseDescription: "Applications of electromagnetic waves.",
    CourseCreditHours: 3,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 31,
    Year: 3,
    SortOrder: 1,
    SubjectAbbreviation: "MATH",
    SubjectIsActive: true,
    CourseNumber: "2305",
    CourseName: "Discrete Math",
    CourseDescription: "Mathematical foundations for computer science.",
    CourseCreditHours: 3,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 32,
    Year: 3,
    SortOrder: 2,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "5367",
    CourseName: "Intro to Comp Architecture Design",
    CourseDescription: "Introduction to computer architecture design.",
    CourseCreditHours: 3,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 33,
    Year: 3,
    SortOrder: 3,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "",
    CourseName: "ECE Elective and Lab",
    CourseDescription:
      "Selected topics in electrical and computer engineering with lab component.",
    CourseCreditHours: 4,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 34,
    Year: 3,
    SortOrder: 4,
    SubjectAbbreviation: "INDE",
    SubjectIsActive: true,
    CourseNumber: "2333",
    CourseName: "Engineering Statistics I",
    CourseDescription:
      "Introduction to probability and statistics for engineers.",
    CourseCreditHours: 3,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 35,
    Year: 3,
    SortOrder: 5,
    SubjectAbbreviation: "ECON",
    SubjectIsActive: true,
    CourseNumber: "2302",
    CourseName: "Principles of Microeconomics",
    CourseDescription: "Basic principles of microeconomics.",
    CourseCreditHours: 3,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 36,
    Year: 4,
    SortOrder: 1,
    SubjectAbbreviation: "COSC",
    SubjectIsActive: true,
    CourseNumber: "2436",
    CourseName: "Programming and Data Structures",
    CourseDescription: "Object-oriented programming and data structures.",
    CourseCreditHours: 4,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 37,
    Year: 4,
    SortOrder: 2,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "4335",
    CourseName: "ECE Design I",
    CourseDescription: "First part of the capstone design project.",
    CourseCreditHours: 3,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 38,
    Year: 4,
    SortOrder: 3,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "3457",
    CourseName: "Digital Electronics",
    CourseDescription: "Advanced topics in digital electronics.",
    CourseCreditHours: 4,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 39,
    Year: 4,
    SortOrder: 4,
    SubjectAbbreviation: "CpE Elect",
    SubjectIsActive: true,
    CourseNumber: "",
    CourseName: "Approved CpE Elective and Lab",
    CourseDescription:
      "Student selects an elective course and lab in computer engineering.",
    CourseCreditHours: 4,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Fall",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 40,
    Year: 4,
    SortOrder: 1,
    SubjectAbbreviation: "GOVT",
    SubjectIsActive: true,
    CourseNumber: "2305",
    CourseName: "U.S. Government",
    CourseDescription:
      "Structure and function of the American federal government.",
    CourseCreditHours: 3,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 41,
    Year: 4,
    SortOrder: 2,
    SubjectAbbreviation: "ECE",
    SubjectIsActive: true,
    CourseNumber: "4336",
    CourseName: "ECE Design II",
    CourseDescription: "Second part of the capstone design project.",
    CourseCreditHours: 3,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 42,
    Year: 4,
    SortOrder: 3,
    SubjectAbbreviation: "CpE Elect",
    SubjectIsActive: true,
    CourseNumber: "",
    CourseName: "Approved CpE Elective and Lab",
    CourseDescription:
      "Student selects an elective course and lab in computer engineering.",
    CourseCreditHours: 4,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 43,
    Year: 4,
    SortOrder: 4,
    SubjectAbbreviation: "COSC",
    SubjectIsActive: true,
    CourseNumber: "4351",
    CourseName: "Fundamentals of Software Engr",
    CourseDescription: "Software development methodologies and practices.",
    CourseCreditHours: 3,
    CourseIsCore: false,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
  {
    ID: 44,
    Year: 4,
    SortOrder: 5,
    SubjectAbbreviation: "CORE",
    SubjectIsActive: true,
    CourseNumber: "",
    CourseName: "Language, Philosophy & Culture",
    CourseDescription:
      "Exploration of topics in language, philosophy, and culture.",
    CourseCreditHours: 3,
    CourseIsCore: true,
    CourseIsActive: true,
    SemesterName: "Spring",
    SemesterSortOrder: 1,
    SemesterIsActive: true,
  },
];
